### ISSUE TITLE
How to generate /build folder

### ISSUE THREAD

**Issue by kmezhoud** [wissem01chiha/ALPR-Cil4Sys-Engineering#3]
Hi,
It is not an issue taht could be labeled by `need help or doc`
I removed `/build` folder while  am thinking that will be generated by `python3 -m build` for `python3 setup.py sdist` , but it is not the case. 
How todo?
Thanks

**Comment by wissem01chiha** [comment]
Hi Dr Karim , sorry for the delay 
if you removed the build folder and you want to regenerate it you should  run   : 

`python setup.py sdist --dist-dir build`

if you run : 

`python3 setup.py sdist`

it will generate the same output (gz.tar file) but under the default created directory dist/ 
 the command `python3 -m build` do the same under the default diractory  dist/ and create .whl and .gz.tar files

if not working try updating/upgrading setuptools and build : 

`pip install --upgrade setuptools`

`pip install --upgrade build`

for more information get to the setuptools offical page at 

[https://setuptools.pypa.io/en/latest/userguide/index.html](url)

i hope you resolve the problem

**Comment by kmezhoud** [comment]
Thanks!,
Only `build/lib/main.py` was generated. All other functions and configs are not generated.

**Comment by kmezhoud** [comment]
in the main.py file we import :
```{python} 
import      transform 
import      utils
import      enhance
import      threshold 
import      video 
import      countour 
import      metric 
```
which are internal module. 
I am trying to write `run_cil4sys` command that runs package from bash. and can parse argument like input option (video.mp4 or live Cam).  In this case, the structure of files must be changed a little bit. And I have to convert main.py file as a function like `def main: ` ... but all internal module in build folder are not recognized.   There an equivalent to `export module` during build that could be recognized  as `cil4sys.transform` , `cil4sys.countour`...?

**Comment by kmezhoud** [comment]
Build is generated during installation and not during build. It is not necessary and we can clean it by `python3 setup.py clean --all`
